### ISSUE TITLE
GLCM MP Broken

### ISSUE THREAD

**Issue by Eve-ning** [Eve-ning/FRModel#39]

**Comment by Eve-ning** [comment]
```
0%|          | 0/472 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johnc\PycharmProjects\FRModel\.scratch\scratch.py", line 12, in <module>
    frame_xy = f.get_chns(xy=True, glcm_verbose=True, glcm_ent=True, glcm_entropy_mp=True)
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 148, in get_chns
    return self.get_all_chns(self_, xy, hsv, ex_g, mex_g, ex_gr, ndi,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel.py", line 208, in get_all_chns
    glcm = self.get_glcm(
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 88, in get_glcm
    self._get_glcm_entropy(rgb_a, rgb_b, radius, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 192, in _get_glcm_entropy
    return self._get_glcm_entropy_mp(cells, out, verbose,
  File "C:\Users\johnc\PycharmProjects\FRModel\src\frmodel\base\D2\frame\_frame_channel_glcm.py", line 227, in _get_glcm_entropy_mp
    p = Pool(procs) if procs else Pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\johnc\AppData\Local\Continuum\anaconda3\envs\FRModel\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
```

**Comment by Eve-ning** [comment]
To add a test here

**Comment by Eve-ning** [comment]
Looking to deprecate this one anyways, unless there's strong requirement for small images (ref. #43) this will not be revived
